// <auto-generated />
using FoodEpos.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodEpos.API.Migrations
{
    [DbContext(typeof(FoodEposDbContext))]
    [Migration("20251013063252_Add meals with meal category")]
    partial class Addmealswithmealcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodEpos.API.Model.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = "13674975-5f6a-4b79-9f17-cfea791d28a2",
                            ImgURL = "https://example.com/images/margherita.jpg",
                            MealCategoryId = -1,
                            Name = "Margherita Pizza",
                            Price = 9.99f
                        },
                        new
                        {
                            Id = "16677470-2c6b-446b-847f-f0b28b46ed0e",
                            ImgURL = "https://example.com/images/caesar.jpg",
                            MealCategoryId = -2,
                            Name = "Chicken Caesar Salad",
                            Price = 8.5f
                        },
                        new
                        {
                            Id = "2b267a03-dfa8-4f40-b0bb-f14b211ec3b4",
                            ImgURL = "https://example.com/images/bolognese.jpg",
                            MealCategoryId = -1,
                            Name = "Spaghetti Bolognese",
                            Price = 11.25f
                        },
                        new
                        {
                            Id = "307b2786-62ac-42e8-8f7b-f2910184e435",
                            ImgURL = "https://example.com/images/salmon.jpg",
                            MealCategoryId = -4,
                            Name = "Grilled Salmon",
                            Price = 14.95f
                        },
                        new
                        {
                            Id = "54835e48-1cec-4163-be1a-030a901e7d85",
                            ImgURL = "https://example.com/images/buddha.jpg",
                            MealCategoryId = -2,
                            Name = "Vegan Buddha Bowl",
                            Price = 10.5f
                        },
                        new
                        {
                            Id = "7d3a1483-002d-42bc-8ef4-18c018b10e12",
                            ImgURL = "https://example.com/images/burger.jpg",
                            MealCategoryId = -1,
                            Name = "Beef Burger",
                            Price = 12f
                        },
                        new
                        {
                            Id = "8b6d9548-287e-404a-984a-dfdf2a39acf3",
                            ImgURL = "https://example.com/images/lava_cake.jpg",
                            MealCategoryId = -6,
                            Name = "Chocolate Lava Cake",
                            Price = 6.75f
                        },
                        new
                        {
                            Id = "ab6f9c58-9df4-4b2c-930a-112eac5d2b91",
                            ImgURL = "https://example.com/images/tomato_soup.jpg",
                            MealCategoryId = -3,
                            Name = "Tomato Soup",
                            Price = 7.25f
                        },
                        new
                        {
                            Id = "c18af6a8-d90b-49e0-bba4-29fce26acaae",
                            ImgURL = "https://example.com/images/garlic_bread.jpg",
                            MealCategoryId = -5,
                            Name = "Garlic Bread",
                            Price = 4.25f
                        });
                });

            modelBuilder.Entity("FoodEpos.API.Model.MealCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealCategories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Hot dishes"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Cold dishes"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Grill"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Appetizer"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("FoodEpos.API.Model.Meal", b =>
                {
                    b.HasOne("FoodEpos.API.Model.MealCategory", "MealCategory")
                        .WithMany("Meals")
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("FoodEpos.API.Model.MealCategory", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
