// <auto-generated />
using FoodEpos.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodEpos.API.Migrations
{
    [DbContext(typeof(FoodEposDbContext))]
    [Migration("20251010075731_Add dummy meals")]
    partial class Adddummymeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodEpos.API.Model.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = "13674975-5f6a-4b79-9f17-cfea791d28a2",
                            ImgURL = "https://example.com/images/margherita.jpg",
                            Name = "Margherita Pizza",
                            Price = 9.99f
                        },
                        new
                        {
                            Id = "16677470-2c6b-446b-847f-f0b28b46ed0e",
                            ImgURL = "https://example.com/images/caesar.jpg",
                            Name = "Chicken Caesar Salad",
                            Price = 8.5f
                        },
                        new
                        {
                            Id = "2b267a03-dfa8-4f40-b0bb-f14b211ec3b4",
                            ImgURL = "https://example.com/images/bolognese.jpg",
                            Name = "Spaghetti Bolognese",
                            Price = 11.25f
                        },
                        new
                        {
                            Id = "307b2786-62ac-42e8-8f7b-f2910184e435",
                            ImgURL = "https://example.com/images/salmon.jpg",
                            Name = "Grilled Salmon",
                            Price = 14.95f
                        },
                        new
                        {
                            Id = "54835e48-1cec-4163-be1a-030a901e7d85",
                            ImgURL = "https://example.com/images/buddha.jpg",
                            Name = "Vegan Buddha Bowl",
                            Price = 10.5f
                        },
                        new
                        {
                            Id = "7d3a1483-002d-42bc-8ef4-18c018b10e12",
                            ImgURL = "https://example.com/images/burger.jpg",
                            Name = "Beef Burger",
                            Price = 12f
                        },
                        new
                        {
                            Id = "8b6d9548-287e-404a-984a-dfdf2a39acf3",
                            ImgURL = "https://example.com/images/lava_cake.jpg",
                            Name = "Chocolate Lava Cake",
                            Price = 6.75f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
